Validação de assinatura
kauehenrick/finance pull request #30
Opened 2024-09-12 02:19 UTC by kauehenrick

Ao realizar o cadastro de usuário, ele recebe um mês de assinatura que fica salvo como o campo "userSubscription". Foi criada uma validação no login para verificar se essa a assinatura do mesmo ainda é válida.

https://github.com/user-attachments/assets/c713b756-77b7-4f1e-bb41-75649af33593

2024-09-12 03:00 UTC, ibotirama commented on src/routes/login.tsx
> +                const isUserSubscribed = isUserRegistered.userSubscription >= new Date();
Não está errado, mas veja. Da linha 77 a linha 82 poderia ser uma função validaAssinatura(), quem lê o código sabe que se o usuário não está registrado então loginValidationPattern(Não entendi bem esse nome) e caso esteja então validaAssinatura. Eu não preciso ler todo o código para entender o que está contecendo, apenas encapsulando as partes em funções com nomes significativos já ajuda na compreensão.

2024-09-12 03:04 UTC, ibotirama requested changes

2024-09-12 03:04 UTC, ibotirama commented on src/routes/login.tsx
> +                    const isUserSubscribed = isUserEmailValid.userSubscription >= new Date();
Aqui o que eu disse anteriormente faz mais sentido ainda porque pelo que entendi o código aqui é repetido, ou seja péssimo sinal, todas as vezes que repetir um código pode pensar(fiz caquinha, tenho que resolver). Se o código se repete seria apenas chamar novamente a função validaAssinatura, que além que mais compreensível, menor evitaria repetições.

2024-09-12 14:32 UTC, kauehenrick commented on src/routes/login.tsx
> +                const isUserSubscribed = isUserRegistered.userSubscription >= new Date();
![image](https://github.com/user-attachments/assets/e70264bb-e2bb-4745-ab40-415d34d43838)

2024-09-12 14:50 UTC, kauehenrick commented on src/routes/login.tsx
> +                const isUserSubscribed = isUserRegistered.userSubscription >= new Date();
Eu acho que ainda não ficou tão legal, mas foi o máximo que consegui abstrair.

2024-09-12 18:04 UTC, ibotirama commented on src/routes/login.tsx
> +                onLogin();
Pq não usou direto 
`handleLogin(user)`
Não tem faz mto sentido uma função cuja a única objetivo é encapsular uma chamada simples para outra função.

2024-09-13 13:00 UTC, kauehenrick commented on src/routes/login.tsx
> +                onLogin();
Foi por conta eu estava me deparando com esse erro.

![image](https://github.com/user-attachments/assets/b85cb3d6-a723-411e-ac9d-b5f0b34cb379)

Erro de principiante, me lembrei como passar o parâmetro na chamada da função:
![image](https://github.com/user-attachments/assets/c65f9b7b-418d-47ee-a1e0-4990d1393317)

2024-09-13 13:47 UTC, ibotirama commented on src/routes/login.tsx
> +                const isUserSubscribed = isUserRegistered.userSubscription >= new Date();
Mas pq não dá pra handleLogin ser uma outra função que é chamada dentro de validateSubscription e precisa ser passada como parametro?

2024-09-13 14:36 UTC, kauehenrick commented on src/routes/login.tsx
> +                const isUserSubscribed = isUserRegistered.userSubscription >= new Date();
A função handleLogin é necessária pois precisa ser utilizada sozinha em outro cenário. Ao em vez de passar a função, passaria o usuário como objeto e repetiria o mesmo código, o que é desnecessário.

Nesse caso, o usuário ainda não está cadastrado.
![image](https://github.com/user-attachments/assets/9f83a76d-2bdb-4754-8078-48c6dea9ea9a)

2024-09-13 18:03 UTC, ibotirama approved these changes

2024-09-13 18:53 UTC, merged